### ISSUE TITLE
Add pullapprove and detail for contribution

### ISSUE THREAD

**Issue by at15** [dyweb/blog#1]
- [x] contribution.md
- [x] pr template
- [x] issue template
- [x] issue labels
- [x] pullapprove integration
- [x] the workflow for submitting a new post

@gaocegege @arrowrowe 

Update

- [x] fix typo `depoly` in `CONTRIBUTING.md` mentioned by @JasonQSY 
- [x] reduce blog reviewer to **2**
- [x] show hint for creating author page when author is not presented
- [x] show yaml to let user copy and paste into `config.yaml`, or use some dark magic to do string replace instead of dump yaml, latter would erase all the comment
- [x] create a team for blog and add to this project's collabrator so more people like @JasonQSY can review

**Comment by arrowrowe** [comment]
Think the last one most important...

**Comment by gaocegege** [comment]
yeah, if someone want to post an article to this blog, just create a new markdown file and run the scripts named "pre-deploy.sh" and commit.

maybe he or she have to add a new author in config.yml If he or she have never posted an article before.

easy, right?

**Comment by gaocegege** [comment]
为什么我们三个菜鸡都要用英语呢

**Comment by JasonQSY** [comment]
Move the workflow to `contribution.md` ?

**Comment by at15** [comment]
@JasonQSY yeah, also need to have the template in `.github` folder, btw: why are u still playing game at this time ....

**Comment by at15** [comment]
some notes for setting up the project. will be merged into readme

-  `go get -u github.com/InkProject/ink`

**Comment by JasonQSY** [comment]
@at15 It seems that some problems happened and the game does not quit normally...

**Comment by gaocegege** [comment]
re @at15 There is no need to have a go environment, we could just download the binary from http://www.chole.io/

**Comment by at15** [comment]
@gaocegege when I execute `create-post.sh` I get the error `scripts/create-post.sh: 8: set: Illegal option -o pipefail`

maybe we should switch to py to avoid all those issues from shell script?

**Comment by gaocegege** [comment]
re @at15 No need, just remove those statements :)

**Comment by at15** [comment]
cc @arrowrowe @gaocegege I have updated the issue, do you mind handle the last item (create new github team) while I handle the rest, thx.

**Comment by arrowrowe** [comment]
@at15 I've created @dyweb/blog and add it as this repo's admin. Leave pullapprove things to you. thx.
