### ISSUE TITLE
[Suggestion] More Posts?

### ISSUE THREAD

**Issue by ComMouse** [dyweb/blog#16]
## Type

- Discuss about more posts on our blog

## Description

Since a semester has ended, we might put some interesting posts in various fields like Web, Distributed System, Fancy Toys, etc. Posts on our blog should be hence encouraged, both to skilled students and freshmen.

A series of tutorials, in my personal view, could be an alternative start.

## Update

TBD

@JasonQSY @gaocegege @vinx13

**Comment by at15** [comment]
````
cat .blogignore
at15
````

:cry:

**Comment by gaocegege** [comment]
@arrowrowe 希望咩可以给我们科普下啥是深度学习
@at15 希望婶婶可以给我们科普下时序数据库的发展

**Comment by at15** [comment]
@gaocegege 希望策策给我们科普一下 processing 除了好看有什么其他优点 /w\

**Comment by at15** [comment]
start working on the tsdb one /w/

And @gaocegege we should have more detail labels for issue, and maybe milestone for each quarter btw: @ComMouse  should encourage new comers (if any) to participate in those things, haven't look at gitlab for a while, guess there isn't much change since last time....

**Comment by ComMouse** [comment]
@at15 Now considering an introduction to the rasterization process in CG....

**Comment by at15** [comment]
@ComMouse 工业豆腿 /w/ 给你带来 IMAX gal ....

**Comment by JasonQSY** [comment]
哇婶婶写数据库了

**Comment by at15** [comment]
@JasonQSY 要不要来玩 stellaris 啊 /w

**Comment by JasonQSY** [comment]
@at15 婶婶也玩吗

**Comment by gaocegege** [comment]
@at15 Processing 这个，Scott 应该比我懂 =。=

我只知道 Processing 是怎么实现的，怎么用 Processing 实现很漂亮的动画，那就不会了

**Comment by at15** [comment]
@JasonQSY  玩啊玩啊 /w\

@gaocegege .... @scottsun94

**Comment by JasonQSY** [comment]
@at15 好啊来玩啊 😄

**Comment by at15** [comment]
I think I'll talk about subtyping in type system and how to implement the type checker in TAPL, current progress can be found in https://github.com/at15/papers-i-read/issues/81, a preview of the notebook can be found in https://github.com/at15/papers-i-read/blob/master/book/tapl/subtyping-presentation.ipynb (github's render has some problem, but it is still readable)

**Comment by at15** [comment]
I think we should add issue labels and create new issues for pending post ideas? cc @gaocegege

**Comment by at15** [comment]
I have added issue labels `area/*` and tagged existing PRs (see #28 as example), feel free to add more and update the status label, cc @gaocegege @ComMouse , I will close this issue now.
